


server:
  port: 28888

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
#        web-admin-password: 123456
        web-allow-others: true


datasource:
  h2:
    tcp-port: 9092
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
#    url: jdbc:h2:tcp://localhost/mem:test;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:mem:test2;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: 123456
    filters: stat
    initialSize: 2
    maxActive: 300
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 200



